# Generated by Django 2.1.7 on 2019-03-20 09:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_field', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
